### ISSUE TITLE
dag action fails trying to import from another file in dag folder

### ISSUE THREAD

**Issue by pindge** [jayamanikharyono/airflow-dag-action#21]
`tests/dags/shared_var.py` contains CONSTANTS that is used by multiple dags within the dag root `AIRFLOW__CORE__DAGS_FOLDER`, but dag-action fails

```
dag_validation.py:25: AssertionError
------------------------------ Captured log call -------------------------------
INFO     root:dag_validation.py:18 DAGs dir : tests/dags
INFO     airflow.models.dagbag.DagBag:dagbag.py:500 Filling up the DagBag from tests/dags
ERROR    airflow.models.dagbag.DagBag:dagbag.py:334 Failed to import: tests/dags/test_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "tests/dags/test_dag.py", line 8, in <module>
    from shared_var import image
ModuleNotFoundError: No module named 'shared_var'
```

**Comment by jayamanikharyono** [comment]
This issue has been added to this release [v2.2](https://github.com/jayamanikharyono/airflow-dag-action/releases/tag/v2.2)
